version: 2.1
executors:
  nodejs:
    docker:
      - image: cimg/node:18.17.1
  golang:
    docker:
      - image: cimg/go:1.20.7

jobs:

  build_and_deploy_controller:
    executor: golang
    steps:
      - checkout
      - run:
          name: Build and Deploy Controller
          command: |
            cd backend/services/controller && go build -o controller cmd/oktopus/main.go
            scp -o StrictHostKeyChecking=no controller $SSH_USER@$SSH_HOST:/home/$SSH_USER
            ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "sudo mv controller /usr/bin/ && sudo systemctl restart controller"
  
  build_and_deploy_mochi:
    executor: golang
    steps:
      - checkout
      - run:
          name: Build Mochi
          command: |
            cd backend/services/mochi/ && go build -o mochi cmd/main.go
            scp -o StrictHostKeyChecking=no mochi $SSH_USER@$SSH_HOST:/home/$SSH_USER
            ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "sudo mv mochi /usr/bin/ && sudo systemctl restart mochi"

  # build_frontend:
  #   executor: nodejs
  #   steps:
  #     - checkout
  #     - run:
  #         name: Build Frontend
  #         command: |
  #           cd frontend/ && npm i && npm run build

  # deploy_controller:
  #   executor: golang
  #   steps:
  #       - run:
  #           name: opa Binary to Server
  #           command: |
  #             ls
  #       - run:
  #           name: Restart Services
  #           command: |
workflows:
  build_and_deploy:
    jobs:
      - build_and_deploy_controller:
          filters:
            branches:
              only: circleci-project-setup
      - build_and_deploy_mochi:
          filters:
            branches:
              only: circleci-project-setup
      # - build_frontend:
      #     filters:
      #       branches:
      #         only: circleci-project-setup
      # - deploy_controller:
      #     requires:
      #       - build_controller
      #     filters:
      #       branches:
      #         only: circleci-project-setup
